#!/bin/bash
###############################################
## generic logon script 
## create symbolic link for each logon host
##

CUR_DIR=${PWD##}
### lookup alias
##http://services.gs.com/api/search/getServicesForEndpoint?GUID=1234567890&Endpoint=hkomqla31.hk.eq.gs.com

#ssh -t luosam@uha.fw.gs.com "pbrun pbgate omaqa@hsaa-1.qa.oma.services.gs.com "
#screen ssh luosam@xtdb-1.qa.oma.services.gs.com
#kinit luosam -k -t ~/luosam.keytab;ssh -t luosam@uha.fw.gs.com "pbrun pbgate omaqa@xtdb-1.qa.oma.services.gs.com "

SELF=$USER@uha.fw.gs.com

function logon {
    ## input host, user
    HOST=$1
    NAME=$2

    if [ -z "$HOST" ]
    then
        echo "no host name specified"
        exit 1
    fi


    if [ -z "$NAME" ]
    then
        ## logon as self
        screen ssh $USER@$HOST
    else
        #ssh -t $SELF "pbrun pbgate $NAME@$HOST.services.gs.com "
        ssh -t $SELF  $NAME@$HOST
        
    fi
}



#ssh -t luosam@uha.fw.gs.com "pbrun pbgate p2eqtwq@syftqla01.ap.eq.gs.com "

#ssh -t luosam@uha.fw.gs.com "pbrun pbgate p2eqtwq@qaeaucea-1.qa.om2.services.gs.com authstate=kerberos"
#kinit luosam -k -t ~/luosam.keytab; ssh -t luosam@uha.fw.gs.com "pbrun pbgate p2eqtwq@qaeaucea-1.qa.om2.services.gs.com "

function usage {

    echo `basename $0` xtdb-1 
    echo `basename $0` xtdb-1 omaqa
    echo `basename $0` hsaa-1 
    echo `basename $0` hsaa-1 omaqa 

}

kinit $USER -k -t ${CUR_DIR}/$USER.keytab


OM2_USER=p2eqtwq
APOLLO_USER=s_aplflh
APOLLO_ROUTER=d_aplrtr
OMA_USER=omaqa

## check basename
case `basename $0` in 
    ## oma
    "XTDb" ) logon "xtdb-1.qa.oma.services.gs.com" $OMA_USER;;
    "XTDz" ) logon "xtdz-1.qa.oma.services.gs.com" $OMA_USER;;
    "HSAa" ) logon "hsaa-1.qa.oma.services.gs.com" $OMA_USER;;
    "XAIa" ) logon "xaia-1.qa.oma.services.gs.com" $OMA_USER;;
    "XDMa") logon "xdma-1.ppe.oma.services.gs.com" $OMA_USER;;
    "XDMa")  logon "xdma-1.qa.oma.services.gs.com" $OMA_USER;;
    "XPSa")  logon "XPSa-1.qa.oma.services.gs.com" $OMA_USER;;
    "XDMd")  logon "xdmd-1.qa.oma.services.gs.com" $OMA_USER;;
    "XDMb")  logon "xdmb-1.qa.oma.services.gs.com" $OMA_USER;;
    "XDMc")  logon "xdmc-1.ppe.oma.services.gs.com" $OMA_USER;;
    "XDMc-qa")  logon "xdmc-1.qa.oma.services.gs.com" $OMA_USER;;

    "ASRa")  logon "asra-1.qa.oma.services.gs.com" $OMA_USER;;
    ## oma RHL6
    "XTDd" ) logon "xtdd-1.qa.oma.services.gs.com" $OM2_USER;;
    "XPXz")logon "xpxz-1.ppe.oma.services.gs.com" $OM2_USER;;
    ## oma hk router
    "hkrouter-1")  logon "hkrouter-1.qa.oma.services.gs.com" $OM2_USER;;
    "hkrouter-2")  logon "hkrouter-2.qa.oma.services.gs.com" $OM2_USER;;

    ## qaautomation host d153578-002.dc.gs.com
    "qaauto-s" ) logon "arhds-s.qa.viking.services.gs.com" $OM2_USER;;
    "qaauto-1" ) ssh -t $SELF $OM2_USER@d225131-001;;
    "qaauto-2" ) ssh -t $SELF $OM2_USER@d225131-002;;
    "qaauto-3" ) ssh -t $SELF $OM2_USER@d225131-003;;
    "qaauto-3" ) ssh -t $SELF $OM2_USER@d225131-004;;

    ## om2
    "om2-1" ) logon "qaeaucea-1.qa.om2.services.gs.com" $OM2_USER;;
    "om2-2" ) logon "qaeaucea-2.qa.om2.services.gs.com" $OM2_USER;;
    ## pme 
    #pmeaucea-1.pp
    ## viking
    "vk-1" ) logon "qaecxaa-p.qa.viking.services.gs.com" $OM2_USER;;
    "vk-2" ) logon "qaecxaa-s.qa.viking.services.gs.com" $OM2_USER;; 
    ## 
    "boc-1" ) logon "boc-qaeaucea-1.qa.om2.services.gs.com" $OM2_USER;;
    "boc-2" ) logon "boc-qaeaucea-2.qa.om2.services.gs.com" $OM2_USER;;
    ## apollo
    "devlh3" ) logon "tkapl-devlh3.tk.eq.gs.com" $OM2_USER;;
    #"appv001") logon "hk-appv001-p.qa.apollo.services.gs.com" $OM2_USER;;
    "appv001") logon "d10836-020.dc.gs.com" $APOLLO_ROUTER;;
    "appv002") logon "d10836-021.dc.gs.com" $APOLLO_ROUTER;;


    *) usage;;
esac

