{'catalog': {'rcsids': ['$Id: catalog.py,v 1.28 2014/11/19 12:34:25 ananas Exp $'],
             'subject': 'catalog',
             'tables': {'HermesCommand': {'columns': {'args': {'index': 2,
                                                               'type': 'string'},
                                                      'argumentVector': {'index': 5,
                                                                         'tablename': 'HermesCommandArgument',
                                                                         'type': 'table'},
                                                      'cmd': {'index': 1,
                                                              'type': 'string'},
                                                      'cmdId': {'index': 6,
                                                                'type': 'int'},
                                                      'guiId': {'index': 4,
                                                                'type': 'int'},
                                                      'handle': {'index': 3,
                                                                 'type': 'string'},
                                                      'requestManager': {'index': 0,
                                                                         'type': 'string'},
                                                      'userId': {'index': 7,
                                                                 'type': 'string'}},
                                          'id': 730},
                        'HermesCommandArgument': {'columns': {'arg': {'index': 0,
                                                                      'type': 'string'}},
                                                  'id': 732},
                        'HermesCommandResult': {'columns': {'args': {'index': 4,
                                                                     'type': 'string'},
                                                            'cmd': {'index': 3,
                                                                    'type': 'string'},
                                                            'cmdId': {'index': 7,
                                                                      'type': 'int'},
                                                            'guiId': {'index': 1,
                                                                      'type': 'int'},
                                                            'handle': {'index': 2,
                                                                       'type': 'string'},
                                                            'message': {'index': 6,
                                                                        'type': 'string'},
                                                            'requestManager': {'index': 0,
                                                                               'type': 'string'},
                                                            'status': {'index': 5,
                                                                       'type': 'string'}},
                                                'id': 731},
                        'catalog': {'columns': {'aliases': {'index': 8,
                                                            'tablename': 'column-alias',
                                                            'type': 'table'},
                                                'always-present': {'index': 7,
                                                                   'type': 'int'},
                                                'column-meta-fields': {'index': 9,
                                                                       'tablename': 'meta-field',
                                                                       'type': 'table'},
                                                'index': {'index': 2,
                                                          'type': 'int'},
                                                'name': {'index': 4,
                                                         'type': 'string'},
                                                'subtable': {'index': 5,
                                                             'type': 'string'},
                                                'table': {'index': 0,
                                                          'type': 'string'},
                                                'table-meta-fields': {'index': 10,
                                                                      'tablename': 'meta-field',
                                                                      'type': 'table'},
                                                'tableid': {'index': 1,
                                                            'type': 'int'},
                                                'type': {'index': 3,
                                                         'type': 'int'},
                                                'width': {'index': 6,
                                                          'type': 'int'}},
                                    'id': 0,
                                    'publishable': 'false'},
                        'column-alias': {'columns': {'alias': {'index': 0,
                                                               'type': 'string'}},
                                         'id': 12,
                                         'publishable': 'false'},
                        'create-dynamic-service-request': {'columns': {'dynamicConfigurationVariablesList': {'index': 2,
                                                                                                             'tablename': 'dynamic-configuration-variable',
                                                                                                             'type': 'table'},
                                                                       'dynamicServiceName': {'index': 0,
                                                                                              'type': 'string'},
                                                                       'dynamicServiceType': {'index': 1,
                                                                                              'type': 'string'}},
                                                           'id': 1504,
                                                           'publishable': 'true'},
                        'create-view': {'columns': {'callbackid': {'index': 0,
                                                                   'type': 'binary',
                                                                   'width': 17},
                                                    'viewFilters': {'index': 2,
                                                                    'tablename': 'view-filter',
                                                                    'type': 'table'},
                                                    'viewName': {'index': 1,
                                                                 'type': 'string'}},
                                        'id': 1002,
                                        'publishable': 'true'},
                        'datastream': {'columns': {'applicationid': {'index': 1,
                                                                     'type': 'string'},
                                                   'callbackid': {'index': 5,
                                                                  'type': 'binary',
                                                                  'width': 17},
                                                   'datastreamname': {'index': 0,
                                                                      'type': 'string'},
                                                   'enums': {'index': 10,
                                                             'tablename': 'table-version',
                                                             'type': 'table'},
                                                   'group': {'index': 3,
                                                             'type': 'string'},
                                                   'instance': {'index': 2,
                                                                'type': 'string'},
                                                   'load': {'index': 6,
                                                            'type': 'int'},
                                                   'messageid': {'index': 4,
                                                                 'type': 'string'},
                                                   'require-processing-acks': {'index': 7,
                                                                               'type': 'int'},
                                                   'require-receipt-acks': {'index': 8,
                                                                            'type': 'int'},
                                                   'tables': {'index': 9,
                                                              'tablename': 'table-version',
                                                              'type': 'table'}},
                                       'id': 1,
                                       'publishable': 'true'},
                        'discovery': {'columns': {'available': {'index': 1,
                                                                'type': 'int'},
                                                  'callbackid': {'index': 0,
                                                                 'type': 'binary',
                                                                 'width': 17}},
                                      'id': 8,
                                      'publishable': 'false'},
                        'dynamic-configuration-variable': {'columns': {'dynamicConfigurationValue': {'index': 1,
                                                                                                     'type': 'string'},
                                                                       'dynamicConfigurationVariable': {'index': 0,
                                                                                                        'type': 'string'}},
                                                           'id': 1503,
                                                           'publishable': 'true'},
                        'enum': {'columns': {'meta-fields': {'index': 2,
                                                             'tablename': 'meta-field',
                                                             'type': 'table'},
                                             'name': {'index': 0,
                                                      'type': 'string'},
                                             'values': {'index': 1,
                                                        'tablename': 'enum-value',
                                                        'type': 'table'}},
                                 'id': 15,
                                 'publishable': 'false'},
                        'enum-value': {'columns': {'name': {'index': 0,
                                                            'type': 'string'},
                                                   'value': {'index': 1,
                                                             'type': 'int'}},
                                       'id': 16,
                                       'publishable': 'false'},
                        'envelope': {'columns': {'message': {'index': 3,
                                                             'type': 'binary'},
                                                 'messageid': {'index': 0,
                                                               'type': 'string'},
                                                 'posdup': {'index': 1,
                                                            'type': 'int'},
                                                 'table': {'index': 2,
                                                           'type': 'ushort'}},
                                     'id': 3,
                                     'publishable': 'false'},
                        'filter-parameter': {'columns': {'filterParameter': {'index': 0,
                                                                             'type': 'string'}},
                                             'id': 1004,
                                             'publishable': 'true'},
                        'image-live': {'columns': {'applicationid': {'index': 1,
                                                                     'type': 'string'},
                                                   'callbackid': {'index': 7,
                                                                  'type': 'binary',
                                                                  'width': 17},
                                                   'enums': {'index': 12,
                                                             'tablename': 'table-version',
                                                             'type': 'table'},
                                                   'eventId': {'index': 6,
                                                               'type': 'string'},
                                                   'group': {'index': 3,
                                                             'type': 'string'},
                                                   'imageLiveName': {'index': 0,
                                                                     'type': 'string'},
                                                   'instance': {'index': 2,
                                                                'type': 'string'},
                                                   'load': {'index': 8,
                                                            'type': 'int'},
                                                   'recordId': {'index': 4,
                                                                'type': 'string'},
                                                   'recordVersion': {'index': 5,
                                                                     'type': 'int'},
                                                   'require-processing-acks': {'index': 9,
                                                                               'type': 'int'},
                                                   'require-receipt-acks': {'index': 10,
                                                                            'type': 'int'},
                                                   'tables': {'index': 11,
                                                              'tablename': 'table-version',
                                                              'type': 'table'}},
                                       'id': 1000,
                                       'publishable': 'false'},
                        'image-live-return-receipt': {'columns': {'callbackid': {'index': 4,
                                                                                 'type': 'binary',
                                                                                 'width': 17},
                                                                  'eventId': {'index': 3,
                                                                              'type': 'string'},
                                                                  'recordId': {'index': 1,
                                                                               'type': 'string'},
                                                                  'recordVersion': {'index': 2,
                                                                                    'type': 'int'},
                                                                  'viewName': {'index': 0,
                                                                               'type': 'string'}},
                                                      'id': 1001,
                                                      'publishable': 'false'},
                        'meta-field': {'columns': {'field': {'index': 0,
                                                             'type': 'string'},
                                                   'value': {'index': 1,
                                                             'type': 'string'}},
                                       'id': 1500,
                                       'publishable': 'false'},
                        'request': {'columns': {'callbackid': {'always-present': 'true',
                                                               'index': 4,
                                                               'type': 'binary',
                                                               'width': 17},
                                                'messagelength': {'always-present': 'true',
                                                                  'index': 5,
                                                                  'type': 'ushort'},
                                                'messagelengthWide': {'always-present': 'true',
                                                                      'index': 6,
                                                                      'type': 'uint'},
                                                'posdup': {'always-present': 'true',
                                                           'index': 1,
                                                           'type': 'ubyte'},
                                                'requestid': {'always-present': 'true',
                                                              'index': 0,
                                                              'type': 'uint'},
                                                'require-receipt-ack': {'always-present': 'true',
                                                                        'index': 3,
                                                                        'type': 'bool'},
                                                'table': {'always-present': 'true',
                                                          'index': 2,
                                                          'type': 'ushort'}},
                                    'id': 5,
                                    'publishable': 'false'},
                        'requestmanager': {'columns': {'applicationid': {'index': 1,
                                                                         'type': 'string'},
                                                       'callbackid': {'index': 4,
                                                                      'type': 'binary',
                                                                      'width': 17},
                                                       'enums': {'index': 8,
                                                                 'tablename': 'table-version',
                                                                 'type': 'table'},
                                                       'group': {'index': 3,
                                                                 'type': 'string'},
                                                       'instance': {'index': 2,
                                                                    'type': 'string'},
                                                       'load': {'index': 5,
                                                                'type': 'int'},
                                                       'requestmanagername': {'index': 0,
                                                                              'type': 'string'},
                                                       'require-receipt-acks': {'index': 6,
                                                                                'type': 'int'},
                                                       'tables': {'index': 7,
                                                                  'tablename': 'table-version',
                                                                  'type': 'table'}},
                                           'id': 2,
                                           'publishable': 'false'},
                        'response': {'columns': {'callbackid': {'always-present': 'true',
                                                                'index': 2,
                                                                'type': 'binary',
                                                                'width': 17},
                                                 'messagelength': {'always-present': 'true',
                                                                   'index': 3,
                                                                   'type': 'ushort'},
                                                 'messagelengthWide': {'always-present': 'true',
                                                                       'index': 4,
                                                                       'type': 'uint'},
                                                 'requestid': {'always-present': 'true',
                                                               'index': 0,
                                                               'type': 'uint'},
                                                 'table': {'always-present': 'true',
                                                           'index': 1,
                                                           'type': 'ushort'}},
                                     'id': 6,
                                     'publishable': 'false'},
                        'return-receipt': {'columns': {'callbackid': {'index': 1,
                                                                      'type': 'binary',
                                                                      'width': 17},
                                                       'messageid': {'index': 0,
                                                                     'type': 'string'}},
                                           'id': 4,
                                           'publishable': 'false'},
                        'service-discovery-config-node': {'columns': {'action': {'index': 4,
                                                                                 'type': 'int'},
                                                                      'configurationNodeIsList': {'index': 0,
                                                                                                  'type': 'int'},
                                                                      'configurationNodeKey': {'index': 1,
                                                                                               'type': 'string'},
                                                                      'configurationNodeValue': {'index': 2,
                                                                                                 'type': 'string'},
                                                                      'configurationNodes': {'index': 3,
                                                                                             'tablename': 'service-discovery-config-node',
                                                                                             'type': 'table'}},
                                                          'id': 1501,
                                                          'publishable': 'true'},
                        'service-discovery-update': {'columns': {'configurationSnapshotDataNode': {'index': 3,
                                                                                                   'tablename': 'service-discovery-config-node',
                                                                                                   'type': 'table'},
                                                                 'configurationSnapshotType': {'index': 4,
                                                                                               'type': 'int'},
                                                                 'serverConfigSnapshotDigest': {'index': 2,
                                                                                                'type': 'string'},
                                                                 'serviceDiscoveryDomainName': {'index': 1,
                                                                                                'type': 'string'},
                                                                 'uniqueApplicationId': {'index': 0,
                                                                                         'type': 'string'}},
                                                     'id': 1502,
                                                     'publishable': 'true'},
                        'table-version': {'columns': {'name': {'index': 0,
                                                               'type': 'string'},
                                                      'version': {'index': 1,
                                                                  'type': 'int'}},
                                          'id': 7,
                                          'publishable': 'true'},
                        'view-cancel': {'columns': {'callbackid': {'index': 0,
                                                                   'type': 'binary',
                                                                   'width': 17},
                                                    'viewName': {'index': 1,
                                                                 'type': 'string'}},
                                        'id': 1005,
                                        'publishable': 'true'},
                        'view-clear-all': {'columns': {'viewName': {'index': 0,
                                                                    'type': 'string'}},
                                           'id': 1011,
                                           'publishable': 'true'},
                        'view-creation-failed': {'columns': {'failureReason': {'index': 2,
                                                                               'type': 'string'},
                                                             'type': {'index': 0,
                                                                      'type': 'int'},
                                                             'viewName': {'index': 1,
                                                                          'type': 'string'}},
                                                 'id': 1006,
                                                 'publishable': 'true'},
                        'view-creation-successful': {'columns': {'type': {'index': 0,
                                                                          'type': 'int'},
                                                                 'viewName': {'index': 1,
                                                                              'type': 'string'}},
                                                     'id': 1007,
                                                     'publishable': 'true'},
                        'view-filter': {'columns': {'filterName': {'index': 0,
                                                                   'type': 'string'},
                                                    'filterParameters': {'index': 1,
                                                                         'tablename': 'filter-parameter',
                                                                         'type': 'table'}},
                                        'id': 1003,
                                        'publishable': 'true'},
                        'view-initialization-commence': {'columns': {'viewName': {'index': 0,
                                                                                  'type': 'string'}},
                                                         'id': 1009,
                                                         'publishable': 'true'},
                        'view-initialization-complete': {'columns': {'viewName': {'index': 0,
                                                                                  'type': 'string'}},
                                                         'id': 1010,
                                                         'publishable': 'true'},
                        'view-notification': {'columns': {'batchAction': {'index': 7,
                                                                          'type': 'ubyte'},
                                                          'eventId': {'index': 6,
                                                                      'type': 'string'},
                                                          'payLoad': {'index': 1,
                                                                      'type': 'binary'},
                                                          'recordId': {'index': 4,
                                                                       'type': 'string'},
                                                          'tableId': {'index': 2,
                                                                      'type': 'int'},
                                                          'type': {'index': 0,
                                                                   'type': 'int'},
                                                          'version': {'index': 5,
                                                                      'type': 'int'},
                                                          'viewName': {'index': 3,
                                                                       'type': 'string'}},
                                              'id': 1008,
                                              'publishable': 'true'}}},
 'channels': {'hermesstandalone': {'connect-to': [{'host': 'd48965-004.dc.gs.com',
                                                   'port': '10302'}]}},
 'client-request-managers': {'PPEAUCEA-Primary': {'applicationid': 'hermes',
                                                  'auto-indicate-availability-load': 100,
                                                  'catalog': ['HermesCommand',
                                                              'HermesCommandResult',
                                                              'HermesCommandArgument'],
                                                  'channel': 'hermesstandalone',
                                                  'request-failure-interval': 300}},
 'hermes': {'groups': {'TEST': ['PPEAUCEA-Primary']},
            'gui-accept-on-port': '10014',
            'replay-limit': '2'},
 'ivcom': {'application-id': 'TEST', 'application-type': 'hermescollector'}}
